# Generated by Django 3.2 on 2023-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230326_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
