# Generated by Django 3.2 on 2023-03-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230326_1624'),
        ('reviews', '0009_auto_20230326_1657'),
    ]

    operations = [
    ]
